WRAP_CLASS("itk::Statistics::Sample" POINTER)
  UNIQUE(dims "1;2;${WRAP_ITK_DIMS}")                    
  FOREACH(d ${dims})
    WRAP_TEMPLATE("${ITKM_FAD${d}}"  "${ITKT_FAD${d}}")
    WRAP_TEMPLATE("${ITKM_FAF${d}}"  "${ITKT_FAF${d}}")
    WRAP_TEMPLATE("${ITKM_FAUL${d}}" "${ITKT_FAUL${d}}")
    WRAP_TEMPLATE("${ITKM_FAUS${d}}" "${ITKT_FAUS${d}}")
    WRAP_TEMPLATE("${ITKM_FAUC${d}}" "${ITKT_FAUC${d}}")
    WRAP_TEMPLATE("${ITKM_FASL${d}}" "${ITKT_FASL${d}}")
    WRAP_TEMPLATE("${ITKM_FASS${d}}" "${ITKT_FASS${d}}")
    WRAP_TEMPLATE("${ITKM_FASC${d}}" "${ITKT_FASC${d}}")
  ENDFOREACH(d)
END_WRAP_CLASS()
