WRAP_NON_TEMPLATE_CLASS("itk::TransformBase" POINTER)

WRAP_CLASS("itk::Transform" POINTER)
  FOREACH(d1 ${WRAP_ITK_DIMS})
    FOREACH(d2 ${WRAP_ITK_DIMS})
      WRAP_TEMPLATE("${ITKM_D}${d1}${d2}" "${ITKT_D},${d1},${d2}")
    ENDFOREACH(d2)
  ENDFOREACH(d1)
END_WRAP_CLASS()

WRAP_CLASS("itk::DataObjectDecorator" POINTER)
  FOREACH(d1 ${WRAP_ITK_DIMS})
    FOREACH(d2 ${WRAP_ITK_DIMS})
      WRAP_TEMPLATE("T${ITKM_D}${d1}${d2}" "itk::Transform< ${ITKT_D},${d1},${d2} >")
    ENDFOREACH(d2)
  ENDFOREACH(d1)
END_WRAP_CLASS()
